function [fitresult, gof] = createFit2(segment2x, segment2y, segment2z)
%CREATEFIT2(SEGMENT2X,SEGMENT2Y,SEGMENT2Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : segment2x
%      Y Input : segment2y
%      Z Output: segment2z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Jul-2018 16:46:27


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( segment2x, segment2y, segment2z );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'Foot Tilt Up' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Foot Tilt Up', 'COM x Position vs. Velocity, Acceleration', 'Location', 'NorthEast' );
% Label axes
title("Foot Tilt Up Phase Affine Fit")
xlabel("Position (m)")
ylabel("Velocity (m/s)")
zlabel("Acceleration (m/s^2)")
grid on
view( -49.1, -58.0 );


