function [fitresult, gof] = createFit3(segment3x, segment3y, segment3z)
%CREATEFIT3(SEGMENT3X,SEGMENT3Y,SEGMENT3Z)
%  Create a fit.
%
%  Data for 'Push Segment' fit:
%      X Input : segment3x
%      Y Input : segment3y
%      Z Output: segment3z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Jul-2018 09:52:31


%% Fit: 'Push Segment'.
[xData, yData, zData] = prepareSurfaceData( segment3x, segment3y, segment3z );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'Push Segment' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Push Segment', 'segment3z vs. segment3x, segment3y', 'Location', 'NorthEast' );
% Label axes
xlabel segment3x
ylabel segment3y
zlabel segment3z
grid on
view( 79.7, -7.6 );


