function [fitresult, gof] = createFit3(segment3x, segment3y, segment3z)
%CREATEFIT3(SEGMENT3X,SEGMENT3Y,SEGMENT3Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : segment3x
%      Y Input : segment3y
%      Z Output: segment3z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Jul-2018 16:47:46


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( segment3x, segment3y, segment3z );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'Foot Tilt Max Height' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Foot Tilt Max Height', 'COM x Position vs. Velocity, Acceleration', 'Location', 'NorthEast' );
% Label axes
title("Foot Tilt Max Height Phase Affine Fit")
xlabel("Position (m)")
ylabel("Velocity (m/s)")
zlabel("Acceleration (m/s^2)")
grid on
view( -34.7, -4.4 );

