function [fitresult, gof] = createFit2(segment2x, segment2y, segment2z)
%CREATEFIT2(SEGMENT2X,SEGMENT2Y,SEGMENT2Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : segment2x
%      Y Input : segment2y
%      Z Output: segment2z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Jul-2018 16:46:27


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( segment2x, segment2y, segment2z );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'segment2z vs. segment2x, segment2y', 'Location', 'NorthEast' );
% % Label axes
% xlabel segment2x
% ylabel segment2y
% zlabel segment2z
% grid on
% view( -49.1, -58.0 );


