function [fitresult, gof] = createFit5(segment5x, segment5y, segment5z)
%CREATEFIT5(SEGMENT5X,SEGMENT5Y,SEGMENT5Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : segment5x
%      Y Input : segment5y
%      Z Output: segment5z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Jul-2018 16:49:01


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( segment5x, segment5y, segment5z );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'Settling' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Settling', 'COM x Position vs. Velocity, Acceleration', 'Location', 'NorthEast' );
% Label axes
title("Settling Phase Affine Fit")
xlabel("Position (m)")
ylabel("Velocity (m/s)")
zlabel("Acceleration (m/s^2)")
grid on
view( -23.9, -40.4 );


