function [fitresult, gof] = createFit4(segment4x, segment4y, segment4z)
%CREATEFIT4(SEGMENT4X,SEGMENT4Y,SEGMENT4Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : segment4x
%      Y Input : segment4y
%      Z Output: segment4z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Jul-2018 16:48:29


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( segment4x, segment4y, segment4z );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'segment4z vs. segment4x, segment4y', 'Location', 'NorthEast' );
% % Label axes
% xlabel segment4x
% ylabel segment4y
% zlabel segment4z
% grid on
% view( -47.9, -25.2 );


